### ISSUE TITLE
gooreplacer chrome版3.3 bug报告

### ISSUE THREAD

**Issue by gggccc44** [jiacai2050/gooreplacer#44]
今天在朋友那发现的，回家我的电脑上也有同样问题，应该是bug

导出功能无效，导入正常

迁移命令无效，难道是因为更新了两次把1的给洗白了？

比较蛋疼的是Extensions Manager看是3.3，浏览器扩展管理看是3.4，商店看是3.5。。。妖怪了，我就当是3.3了

**Comment by jiacai2050** [comment]
最近升级是比较频繁，可以升到 3.5 再试试，我这边一直都是 OK 的。

**Comment by gggccc44** [comment]
嗯，重启了下浏览器迁移命令有效了，看了下是3.5，估计那个版本问题和没重启有关

导出还是没反应，看了下控制台一堆红色可能和我装的扩展或者脚本有关吧，我猜，下盘再测试

贴出来给你看看，我估计是和我装的去广告去弹窗有关

Uncaught TypeError: Failed to construct 'Blob': The 1st argument is neither an array, nor does it have indexed properties.
    at gB (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:891:224)
    at Object.r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:35:5860)
    at i (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:22344)
    at Object.s [as executeDispatchesInOrder] (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:22559)
    at f (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:18941)
    at m (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:19067)
    at Array.forEach (native)
    at r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:36:12490)
    at Object.processEventQueue (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:20125)
    at r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:35:6109)

**Comment by jiacai2050** [comment]
你可以看看 Option 页面的 localStorage，截图我看看
![image](https://user-images.githubusercontent.com/3848910/32401749-63fb470e-c150-11e7-8e39-a2f8ca5cdfff.png)

**Comment by jiacai2050** [comment]
如果没问题，这个先关了，有问题再开吧。
