### ISSUE TITLE
在国内双核浏览器上导出配置

### ISSUE THREAD

**Issue by gzl6** [jiacai2050/gooreplacer#56]
配置导出功能在chrome上没有问题。

但是国内的chrome双核浏览器，点击导出按钮没有反应。建议作者优化。
或者如果受限，那么利用代码在屏幕上输出配置，用户可以自己剪贴后自己另存为.gson亦可

**Comment by jiacai2050** [comment]
是国内什么浏览器，可以 F12 打开控制台，然后点击导出，看看报什么错。
我想了下，可以加个函数，直接在控制台执行，输出规则。

**Comment by gzl6** [comment]
360浏览器
QQ浏览器

报错信息：

main.js:1372 Uncaught TypeError: Failed to construct 'Blob': The 1st argument is neither an array, nor does it have indexed properties.
    at pz (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:1372:220)
    at n.handleClick (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:607:48892)
    at Object.r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:35:5860)
    at i (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:22344)
    at Object.s [as executeDispatchesInOrder] (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:22559)
    at f (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:18941)
    at m (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:19067)
    at Array.forEach (native)
    at r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:36:12490)
    at Object.processEventQueue (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:20125)

**Comment by jiacai2050** [comment]
在这些国内浏览器，你是通过什么渠道安装的？
这个报错不应该出现的呀

**Comment by gzl6** [comment]
官网安装的

360信息
Uncaught TypeError: Failed to construct 'Blob': The 1st argument is neither an array, nor does it have indexed properties.
    at pz (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:1372:220)
    at n.handleClick (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:607:48892)
    at Object.r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:35:5860)
    at i (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:22344)
    at Object.s [as executeDispatchesInOrder] (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:22559)
    at f (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:18941)
    at m (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:19067)
    at Array.forEach (native)
    at r (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:36:12490)
    at Object.processEventQueue (chrome-extension://jnlkjeecojckkigmchmfoigphmgkgbip/option/main.js:33:20125)

QQ浏览器
main.js:1372 Uncaught TypeError: Failed to construct 'Blob': The 1st argument is neither an array, nor does it have indexed properties.pz @ main.js:1372n.handleClick @ main.js:607r @ main.js:35i @ main.js:33s @ main.js:33f @ main.js:33m @ main.js:33r @ main.js:36processEventQueue @ main.js:33r @ main.js:35handleTopLevel @ main.js:35a @ main.js:35perform @ main.js:36batchedUpdates @ main.js:35a @ main.js:35dispatchEvent @ main.js:35

搜狗浏览器
Uncaught ReferenceError: sogouExplorer is not defined
main.js:35 Uncaught TypeError: Failed to construct 'Blob': The 1st argument is neither an array, nor does it have indexed properties.
main.js:1372 Uncaught TypeError: Failed to construct 'Blob': The 1st argument is neither an array, nor does it have indexed properties.pz @ main.js:1372n.handleClick @ main.js:607r @ main.js:35i @ main.js:33s @ main.js:33f @ main.js:33m @ main.js:33r @ main.js:36g.processEventQueue @ main.js:33r @ main.js:35a.handleTopLevel @ main.js:35a @ main.js:35a.perform @ main.js:36d.batchedUpdates @ main.js:35a @ main.js:35m.dispatchEvent @ main.js:35

**Comment by jiacai2050** [comment]
具体网址多少，我并没有向这些国内网站上传。猜测是不是别人修改后上传的。

**Comment by gzl6** [comment]
Sorry:
我以为你问的是浏览器哪里下载的。
插件是在https://chrome-extension-downloader.com/下载的

**Comment by gzl6** [comment]
![image](https://user-images.githubusercontent.com/20939122/34859150-76e9a61a-f78f-11e7-862b-14dedb93c1b3.png)

**Comment by jiacai2050** [comment]
谢谢，看来还是兼容性的问题，这个周末我再看看怎么解决。

**Comment by gggccc44** [comment]
国内双核很多要修改才能兼容，360，百度，猎豹，搜狗估计都要修改，看到广告净化器就是弄了多个版本

**Comment by jiacai2050** [comment]
嗯，你有兴趣解决这个问题嘛？

**Comment by gggccc44** [comment]
我只会找问题，不会解决(*^◎^*)

**Comment by ArcticLampyrid** [comment]
最新版QQ浏览器未能重现该错误

**Comment by jiacai2050** [comment]
> 最新版QQ浏览器未能重现该错误

Great
